# Shell variables
# Generated by 'wal'
wallpaper="/home/rafaelmercado/Arte.gif"

# Special
background='#081A2B'
foreground='#c1c5ca'
cursor='#c1c5ca'

# Colors
color0='#081A2B'
color1='#5A6591'
color2='#036FC2'
color3='#8D77A0'
color4='#259EA6'
color5='#2893B9'
color6='#5496B2'
color7='#c1c5ca'
color8='#5e6974'
color9='#5A6591'
color10='#036FC2'
color11='#8D77A0'
color12='#259EA6'
color13='#2893B9'
color14='#5496B2'
color15='#c1c5ca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
