--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/rafaelmercado/Arte.gif"

-- Special
background="#081A2B"
foreground="#c1c5ca"
cursor="#c1c5ca"

-- Colors
color0="#081A2B"
color1="#5A6591"
color2="#036FC2"
color3="#8D77A0"
color4="#259EA6"
color5="#2893B9"
color6="#5496B2"
color7="#c1c5ca"
color8="#5e6974"
color9="#5A6591"
color10="#036FC2"
color11="#8D77A0"
color12="#259EA6"
color13="#2893B9"
color14="#5496B2"
color15="#c1c5ca"
