[colors.primary]
background = "#081A2B"
foreground = "#c1c5ca"

[colors.cursor]
text = "#081A2B"
cursor = "#c1c5ca"

[colors.vi_mode_cursor]
text = "#081A2B"
cursor = "#c1c5ca"

[colors.search.matches]
foreground = "#081A2B"
background = "#c1c5ca"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5e6974"
background = "#c1c5ca"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#081A2B"
red = "#5A6591"
green = "#036FC2"
yellow = "#8D77A0"
blue = "#259EA6"
magenta = "#2893B9"
cyan = "#5496B2"
white = "#c1c5ca"

[colors.bright]
black = "#5e6974"
red = "#5A6591"
green = "#036FC2"
yellow = "#8D77A0"
blue = "#259EA6"
magenta = "#2893B9"
cyan = "#5496B2"
white = "#c1c5ca"

[colors.dim]
black = "#c1c5ca"
red = "#5A6591"
green = "#2893B9"
yellow = "#8D77A0"
blue = "#259EA6"
magenta = "#036FC2"
cyan = "#5496B2"
white = "#5e6974"

